---
title: "Assignment 1"
date: "2022-10-17"
output: html_document
---

# About Me
Hello everyone. I am Gülhan and I am currently working as a mathematics teacher. I have a mathematics education undergraduate degree from Boğaziçi University. I started to interest data as a hobby. In my trip of data, there were several areas to learn. One of them was Python which is a computer language to analyze data. Last February, I started the "100 Days of Code: The Complete Python Pro Bootcamp for 2022" certification program on Udemy. In addition to Python, HTML and CSS are also explained in the training. I was taking the training for a few hours every day after work. As the days progressed in the training, I started to enjoy it more and I spent 4-5 hours each evening and completed the training. Then, I started different training courses on data analytics on Udemy. I started two different courses, first in the statistics section and then in the field of SQL to improve my knowledge in both data extraction and analysis. As time passed, I was sure that I should do this job. However, after 5 years of teaching experience and because I do not have an academic background in data, I decided to pursue a master's degree. So that's why I'm here :)
Here is my [Linkedin](https://www.linkedin.com/in/g%C3%BClhan-demirel-75a026bb/) profile


# rstudio::conf(2022)
## Garbage Data, And What To Do About Them by Jim Kloet
This video is about bad data. According to video bad data is the data that cannot be used for analysis or decision making. It identifies the challenges that you face while dealing with garbage data and suggest a framework to examine the bad data.
Here are the steps:
1. Identify the garbage data: They are not usefull for the things you want to do, but maybe they are usefull for other stuff. You need to decide. If you chose none of them, you can destroy it.
2. Identify the costs of garbage data: Some costs are unavoidable and some costs are avoidable, but these can be catastrophic.
3. Take action when you see garbage data: There are options like being honest to your stakehoulders and being emphatatic to your stakehoulders to continue to have stakehoulders.

# 3-R Posts
## 1-Creating your career with R – data science based jobs!
It indicates that your industry and geographical location are the crucial factors that affect your career. That's why a person who wants to improve modern data analytics skills like Hadoop, Weka, Natural Language Processing or Machine Learning should be in the countries that is open to new things. However, if you are living in a conservative country, SQL helps you to find a job. It says that R is the best way to start data based career and it should be supported by some other programs like SQL and Hadoop.

[Post Link:](http://r-tutorials.com/creating-your-career-with-r-data-science-based-jobs/)

## 2-Top Job Boards for R users to take your career to the next level!
The post says that R is one of the most important programming languages for Data Science applications. According to post, R is used for data manipulation, business analytics, machine learning algorithms and data visualization techniques. 
Here are some job boards that offers jobs in the fields of data science with R programming skills:
R-users.com
Dice
CareerBuilder
LinkedIn
Indeed
Monster
Naukri
Timesjobs

[Post Link:](https://www.r-users.com/blog/)


```{r}

```
